version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}
  
  postgres_data_dev2: {}
  postgres_backup_dev2: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - DB_USER=pyconnigeria
      - DB_PASS=postgres
      - DB_NAME=pyconnigeria
    ports:
      - "5448:5432"

  db:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev2:/var/lib/postgresql/data
      - postgres_backup_dev2:/backups
    environment:
      - DB_USER=pyconnigeria
      - DB_PASS=postgres
      - DB_NAME=pyconnigeria
    ports:
      - "5550:5432"

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
    restart: always
    environment:
      - POSTGRES_USER=pyconnigeria
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgres://pyconnigeria:postgres@postgres/pyconnigeria
      - USE_DOCKER=yes
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - "8007:8000"
    links:
      - postgres

      - mailhog




  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

